// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdsLFwDKGK_eWrrnjzki6-8BZrQX2bOE8',
    appId: '1:1045008187828:web:2c8d3cc42d5dde2d2a72e1',
    messagingSenderId: '1045008187828',
    projectId: 'flutter-rest-starter',
    authDomain: 'flutter-rest-starter.firebaseapp.com',
    databaseURL: 'https://flutter-rest-starter.firebaseio.com',
    storageBucket: 'flutter-rest-starter.appspot.com',
    measurementId: 'G-QKQ4EBCKGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI0FDohQ6jsP5EoCkOinBUCKnEpH-Ru18',
    appId: '1:1045008187828:android:77fa54521af103f42a72e1',
    messagingSenderId: '1045008187828',
    projectId: 'flutter-rest-starter',
    databaseURL: 'https://flutter-rest-starter.firebaseio.com',
    storageBucket: 'flutter-rest-starter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1hfw_MSPsRs1fRnyyWjk1kCGpKIKJuXc',
    appId: '1:1045008187828:ios:dc3aed6b961292892a72e1',
    messagingSenderId: '1045008187828',
    projectId: 'flutter-rest-starter',
    databaseURL: 'https://flutter-rest-starter.firebaseio.com',
    storageBucket: 'flutter-rest-starter.appspot.com',
    iosClientId:
        '1045008187828-shfue9h8a969b7q678sd671d91h4ln8q.apps.googleusercontent.com',
    iosBundleId: 'dev.danvickmiller.flutterboilerplate',
  );
}
